on: [push, pull_request]

name: Deny

jobs:
  clippy:
    name: deny
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: install cargo deny
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deny
      - name: cargo deny check
        uses: actions-rs/cargo@v1
        with:
          command: deny
          args: check
